$terminal = kitty
$term = kitty
$files = thunar
$menu = hyprlauncher

# webapp
$teams = "chromium --app='https://teams.cloud.microsoft/v2' --class=Teams --name=Teams"
$outlook = "chromium --app='https://outlook.office.com' --classe=Outlook --name=Outlook"
$atera = "chromium --app='https://app.atera.com' --class=ATERA --name=ATERA"
