windowrule = workspace 10, match:class [vV]esktop
windowrule = workspace 9, match:class [sS]potify
windowrule = workspace 8, match:class [fF]irefox
windowrule = workspace 7, match:class steam.*
windowrule = workspace 2, match:class [zZ]ed

# Web Apps - Chromium
windowrule = workspace 6, match:class ^(chrome-app.atera.com__-Default)$
windowrule = workspace 5, match:class ^(chrome-outlook.office.com__-Default)$
windowrule = workspace 4, match:class ^(chrome-teams.cloud.microsoft__v2-Default)$

windowrule = size 1800 1000, match:class steam, match:title Steam
windowrule = size 350 800, match:class steam, match:title Friends List

# Alacritty (pour les MAJ, btop & bluetui)
windowrule = tag +btop, match:title [aA]lacritty
windowrule = size 1430 850, match:tag btop*
windowrule = float on, match:tag btop*
