windowrule = workspace 10, match:class [vV]esktop
windowrule = workspace 9, match:class [sS]potify
windowrule = workspace 8, match:class [fF]irefox
windowrule = workspace 7, match:class steam.*
windowrule = size 1800 1000, match:class steam, match:title Steam
windowrule = size 350 800, match:class steam, match:title Friends List

# Btop
windowrule = tag +btop, match:title [aA]lacritty
windowrule = size 1430 850, match:tag btop*
windowrule = float on, match:tag btop*


